server:
  port: 8001
spring :
   application :
      name : feignService  
   zipkin:
     base-url: http://localhost:7777
     locator:
        discovery:
            enabled: true
   sleuth:
    sampler:
      probability: 1.0
    enabled: true      #表示当前程序使用sleuth  
    web:  
      skipPattern : (^cleanup.*) 


eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/   
       
      
feign:
  hystrix:
    enabled: true